"""add structure inclination fields

Revision ID: d9f4ae58e1c6
Revises: 
Create Date: 2026-02-14 17:40:31.425774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f4ae58e1c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('structures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beam_inclination_deg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('inclination_start_beam', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inclination_end_beam', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('show_post_labels', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('structures', schema=None) as batch_op:
        batch_op.drop_column('show_post_labels')
        batch_op.drop_column('inclination_end_beam')
        batch_op.drop_column('inclination_start_beam')
        batch_op.drop_column('beam_inclination_deg')

    # ### end Alembic commands ###
